### ISSUE TITLE
Fetch swappable tokens for Nabla swap

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#112]
As a user, I should be able to see all the tokens that can be swapped in the swap dropdown

## Acceptance criteria
* on `/nabla/swap`
* In the dropdown show tokens/assets that can be swapped with other tokens. 
* For ex. if USDC is swappable with USDT then if the user selects USDC in the first dropdown, they must be able to see USDT in the second dropdown. 

### Notes
More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
@nejcm Will talk with Andy for more inputs.

**Comment by ebma** [comment]
## Technical refinement

This is the same as fetching swap pools. Since the Router contract stores this info with a `mapping` internally and we cannot list all elements of that `mapping` without knowing the addresses, we cannot fetch that info automatically (without an indexer) and would have to hard-code the known addresses into the UI for now.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/112?planning-poker) with Zenhub @nejcm @ebma

**Comment by prayagd** [comment]
Closing this as this is a older ticket
