### ISSUE TITLE
Fetch user liquidity info for Nabla backstop pool

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#118]
As a portal user, I should be able to see my amount deposited in the backstop pool. 

## Acceptance criteria
* On `/backstop-pools`
* Show the amount deposited by the user in the backstop pool

## Technical consideration
* How to fetch the backstop pool info?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/118?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by TorstenStueber** [comment]
## Technical refinement

We can't see the actual amount deposited but we can display the redeemable amount (which is roughly the same but the redeemable amount can be higher because the liquidity provider participated in swap fees).

* first call the method `balanceOf` of the backstop pool contract specifying the address of the user
* with the return result ("shares") call the method `sharesTargetWorth` specifying "shares" as the argument
* display the returned value

**Comment by prayagd** [comment]
Closing older ticket
