### ISSUE TITLE
Remove liquidity from the Nabla backstop pool 

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#141]
As a 0xAmber user, I should be able to remove liquidity from the 0xAmber backstop pool. 

## Acceptance criteria
* On `/backstop-pools`
* Show `Remove liquidity` option for the pool
* On clicking it, show pop-up to enter the amount. 
* On confirm, the transaction to add liquidity should be executed. 
* Allow withdrawing in any other assets that the backstop pool is connected to (connected swap pools)

## Technical consideration
*  How to execute the transaction to remove liquidity from the backstop pool?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
cc @nejcm

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/141?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by nejcm** [comment]
This task contains some bullet points/subtasks that were already completed like the modal popup. UI is prepared

**Comment by TorstenStueber** [comment]
## Technical refinement

To add liquidity call the method `withdraw` of the backstop pool contract and specify
* the number of shares (which is the amount of liquidity pool tokens)
* the minimum amount (let us use 0 here)

Since the method takes the number of shares, we would need to calculate that from the amount of backstop pool tokens the user specified.
* shares = totalSupply() / totalLiabilities * amount
