### ISSUE TITLE
Remove liquidity from Nabla swap pool

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#142]
As 0xAmber user, i should be able to remove liquidity from the swap pools. 

## Acceptance criteria
* On `/swap-pools`
* Show table of pools
* On clicking `Withdraw`
* Show pop-up for removing liquidity
* On this pop-up fetch these details
    * Wallet balance
    * Amount withdrawing(after fee)
    * Penalty*
    * Minimum amount recieved
    * Remaining deposits in the pool
    * Remaining pool share - User share in the pool
* On confirming the withdraw, the transaction to remove liquidity in the 0xAmber swap pool should be executed. 

## Technical consideration
* How to fetch the above info?
* How to execute the transaction to remove liquidity from swap pools?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
cc @nejcm

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/142?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by nejcm** [comment]
This task contains some bullet points/subtasks that were already completed like the modal popup. UI is prepared

**Comment by TorstenStueber** [comment]
@prayagd the definitions
* Wallet balance
* Effective deposit
* Reward/penalty
Are unclear to me. Also: is the pool share an absolute number or a percentage?

**Comment by TorstenStueber** [comment]
## Technical refinement

For the actual removal of liquidity: To remove liquidity call the method `withdraw` of the backstop pool contract and specify
* the number of shares (which is the amount of liquidity pool tokens)
* the minimum amount (let us use 0 here)

Since the method takes the number of *shares*, we would need to calculate that from the *amount* of backstop pool tokens the user specified.
* to this end, first read
  * the `totalLiabilities`, which is the second argument returned from the `coverage()` method
  * the `totalSupply`, which is returned from the `totalSupply()` method

Then *shares* = `totalSupply` / `totalLiabilities` * *amount*
