### ISSUE TITLE
Show $AMPE balance on dashboard

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/portal#16]
As a user connected with a wallet, show on `/dashboard` my $AMPE balance (no historic data)

In this version, only the current $AMPE balance is shown, no other graphs or similar

**Comment by erasmus** [comment]
@ebma @b-yap can you please help figure out how to fetch account balances from the Amplitude RPC endpoint

**Comment by ebma** [comment]
Amplitude currently still uses the balances pallet. To query balances for an account from it, simply use `api.query.balances.account(some_accountId)` on the `api` object exposed from polkadot.js

See https://polkadot.js.org/docs/substrate/storage/#balances

**Comment by prayagd** [comment]
@nicolasdanelon Can you hide the TVL graph and on the portfolio only show the AMPE balance. You can also remove the tokens listed there i.e PEN and USDC and the timeline too.

**Comment by prayagd** [comment]
@gonzamontiel Can you help Nicolas get some AMPE on rococo or either on the Amplitude network?

**Comment by TorstenStueber** [comment]
@ebma For some reasons the balance state is not maintained in the balances pallet but it is delegated to the system pallet storage so that we actually need to query the state `api.query.system.account`.

This behavior is standard among parachains and templates: https://github.com/substrate-developer-hub/substrate-node-template/blob/main/runtime/src/lib.rs#L250

**Comment by ebma** [comment]
@TorstenStueber okay great, thanks for pointing it out.
