### ISSUE TITLE
Revamp connect wallet flow and design

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#28]
As a portal user, i should be able to connect the wallet to Portal

## Acceptance criteria
* Show "Connect Wallet" option on the top right corner of Portal
* on clicking "Connect Wallet"
    * Show a modal to with all the wallet options
    * User should be able to select one of the options
    * on selecting, show all the available accounts from selected wallet that the user wants to connect
    * User should be able to select one option our of the available wallets
    * on successful connection show the "Wallet Connected" pop-up
    * on closing the pop-up on the top right corner the user should be able to see the connected account
* Unhappy Path
    * If the user does not have the available wallet option and selects one option
    * Show "Extension not installed" pop-up error
    * "Download polkadot.js extension here." clicking on here show redirect to the installation page of the extension
    * Links shared in the notes section
    * Once the user installs, on clicking "Reconnect" redirect the user to the wallet options modal for the selection.

## Notes
* Installation links
* Subwallet - https://www.subwallet.app/download.html
* Talisman - https://chromewebstore.google.com/detail/talisman-ethereum-and-pol/fijngjgcjhjmmpcmkeiomlglpeiijkld
* Polkdot.js - https://polkadot.js.org/extension/ 
* Walletconnect option does not need any link, the existing flow is good.
* This ticket is for implementation of both Pendulum and Amplitude only desktop designs
* This is to update the design and logic too, the current implementation is done using the https://github.com/TalismanSociety/talisman-connect 

## Wireframe
* Only implement the designs titled with `Connect Wallet` - https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=3988-5130&mode=design&t=lDlS61kKfepi1u2A-4

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/28?planning-poker) with Zenhub @ebma @gonzamontiel @Sharqiewicz

**Comment by prayagd** [comment]
Next ticket related to the feature is [here](https://github.com/pendulum-chain/portal/issues/340)

**Comment by prayagd** [comment]
@ebma as this ticket is about updating both the design and the logic, should i create a different ticket for first implementing the logic as currently we are using the talisman connect library for the wallet plugins? cc @Sharqiewicz

**Comment by ebma** [comment]
I think it's fine to change both logic and design in one go. 
In order to help you get started I want to give you some more context @Sharqiewicz. We are currently using a wallet-select dialog component implemented by the talisman team, see [here](https://github.com/pendulum-chain/portal/blob/98e65940ecc2961001831b7a423303d8d8438550/src/components/Wallet/index.tsx#L61). This component is exposed by one of many [packages](https://github.com/TalismanSociety/talisman-connect/tree/master) developed by talisman to facilitate wallet connections for dapp developers. We want to replace this dialog with our own though because it's too limited and some things are not working properly e.g. you cannot scroll through the list of accounts if you have imported a lot of them. The links to the other wallet extensions that @prayagd put into the description probably will not help you much for the implementation. I would recommend that you have a look at the code for the underlying connection logic of the talisman components that we are trying to replace because they already nailed that part.
