### ISSUE TITLE
Spacewalk token selection dropdown disappers

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#321]
### Describe the bug

On /spacewalk/bridge. If the user keeps the screen inactive for some period of time, the token selection dropdown disappears. 

### Reproduction

1. Go to /spacewalk/bridge
2. Click on "To Amplitude"
3. Leave the tab and keep it inactive
4. The token dropdown disappers from the screen

### Expected behavior

Token dropdown should not disappear

### Screenshots

![image](https://github.com/pendulum-chain/portal/assets/52105313/3ccc8d8a-a442-4b63-a45d-08cc9c35fd5b)

**Comment by gonzamontiel** [comment]
Ok, so I tested it leaving a tab open the whole night, and the dropdown is still there. My guess is that the inactive tab may lose connection (because the browser doesn't want to waste it on an inactive tab) and then, the call to receive the vault assets fails, giving an empty result. As a consequence, the dropdown doesn't have tokens to show, and hides. We could try to solve this, but I see it rarely happening. Let's keep it in the backlog for a while until it is a bigger problem.

**Comment by prayagd** [comment]
Agree @gonzamontiel , Moving it to being prepared.

**Comment by vadaynujra** [comment]
@prayagd what is the status of this ticket? Still required? And when?

**Comment by vadaynujra** [comment]
@prayagd any update on the above question?

**Comment by prayagd** [comment]
Closing as this was one time thing and never occurred again
