### ISSUE TITLE
Change the text on Back to stellar pop-up window

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#409]
### User story
As a user I want to see a message in the Back to Stellar pop-up window indicating that the transaction typically takes only a few minutes, so that I am not expecting the time span to be up to 6 hours.

<img width="519" alt="Screenshot 2024-04-15 at 14 36 03" src="https://github.com/pendulum-chain/portal/assets/138758794/fe7e3739-3cf6-4e83-a138-74fe94eb0280">

### Requirement 
The text should be changed to: This typically takes only a few minutes. Contact [support](https://t.me/pendulum_chain) if your transaction is still pending after 10 minutes.

**Comment by vadaynujra** [comment]
@annatekl what do you refer to with PEN payment?

**Comment by vadaynujra** [comment]
@annatekl I think it's worth taking this opportunity to ensure we update the message to the best of our knowledge and intention. Agree? If yes, let us make sure we fully understand why we're asking for what is under the requirement section. 
Since you are well aware of the redeem flow, can you tell me what you want to communicate to the user based on the phrase - when PEN payment is executed?

**Comment by annatekl** [comment]
@Sharqiewicz I have updated text in the description
