### ISSUE TITLE
Screen freezes when manually selecting vault for EURC on Spacewalk

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/portal#445]
Which user interface was the bug observed on?
Portal Spacewalk Bridge settings wheel crashes the interaction

What steps did you take?
Portal
Bridge
Change Asset to EURC
Settings wheel
Check manually select vault
UI freezes nothing else possible to select click or get out of the menu

What was the outcome you expected?
Not freezing, or being able to revert everything, not need to refresh page

What was the outcome you observed?
UI freezes nothing else possible to select click or get out of the menu
Screenshot of the bug / error message
https://satoshipay.slack.com/files/UA3GK5K9P/F073A8FJ0CD/bridge_settings_bug.jpg

Account address that is facing the bug/issue
no wallet or account was connected

Criticality of the bug
Medium

What device were you on?
Desktop

Device model
Macbook Pro 14 M1Pro

OS
MacOS

Browser and its version
Chrome

Additional information regarding the bug
Seems that there is just one, so actually no option, maybe just adjust or avoid the selection (manually the vault)

**Comment by ebma** [comment]
I can confirm and reproduce the bug. Seems to happen with all non-XLM currencies though. Possibly because the max issuable amount of the XLM vault is 0 at the moment, so this doesn't cause any problems.
@Sharqiewicz I took a picture of the console logs, can you please look into this?
<img width="1525" alt="image" src="https://github.com/pendulum-chain/portal/assets/6690623/31bac98f-185f-4ec1-85f6-37044b519660">
