### ISSUE TITLE
Approve button does not appear again for new swap after successful swap

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#467]
### Describe the bug

When a user completes a Nabla swap and now changes the source token and does not change the source amount, the `Approve` button does not show up and directly a `Swap` button is displayed on clicking `Swap` button the transaction fails.

### Reproduction

1. Go to https://portal.pendulumchain.org/foucoco/nabla/swap
2. Select any source token and destination token and do a swap
3. Now change the source token and dont change the amount, the UI shows a swap button
4. On clicking the Swap button, the UI throws and error

### Expected behavior
Approve button should show before every new swap to be done assuming the Approval was not done for the specific pair and amount

**Comment by ebma** [comment]
@prayagd Are you sure that this is still a problem? 
I tried to reproduce this with the steps you outlined in the description. What I did:
- Navigate to the Forex AMM tab on Foucoco
- Connect the joint-tech product account (`6mYqNJsaGLNduqMdBFhj3ZdzkLy9kghThEUHE3MswphpoATv`)
- Select 'AMPE' as the source token and 'BRL' as the target
- Enter an amount of 1 AMPE and approve the swap
- Change the source token to something other than BRL, e.g. 'Mock USDC'. 

The button will change back to 'Approve'.

@prayagd Maybe you had a special case where your account just approved enough of that token before so that it didn't show the approve button again? But then the swap wouldn't have failed as you describe in the description. I don't know, maybe you can try reproducing this again, and add the account you used + the specific tokens to your description?

**Comment by prayagd** [comment]
@ebma Let me share a loom recording of this

**Comment by prayagd** [comment]
@ebma hahaha, i checked now and i am not able to reproduce the issue again, lets close we can reopen if it occurs again
