### ISSUE TITLE
Approve button invisible while loading

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#468]
### Describe the bug

When a user does a swap and clicks on the Approve button, the button disappers while loading

### Reproduction

1. Go to https://portal.pendulumchain.org/foucoco/nabla/swap
2. Select a pair to approve
3. After clicking on the Approve button, the button diappears

### Expected behavior

The approve button should be visible while loading and change to swap after successfull approving

### Screenshots

https://github.com/pendulum-chain/portal/assets/52105313/e7de7cfc-c9a9-45d4-a746-2d4567795022

### Desktop (please complete the following information):

- OS: iOS
- Browser: Chrome

**Comment by TorstenStueber** [comment]
The button does not disappear. It becomes disabled because the UI first needs to load the return amount. During that time it shows a spinner on the button. It seems that the spinner here is just way too big and takes over the whole button (that's why there is this weird animation happening). This seems to be a bug with daisyui that is responsible to render the spinner (using the `loading` css class).
