### ISSUE TITLE
Remove 50% and Max from the Backstop pool withdraw UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#478]
## Context
Currently the max values are not calculated properly in the Backstop pool(BSP) withdraw UI

## Requirement
* Remove the 50% and Max options from 
    * backstop pool withdrawal (return backstop pool LP tokens and receive backstop pool tokens)
    * swap pool withdrawal (return swap pool LP tokens and receive swap pool tokens)
    * backstop redeem (return swap pool LP tokens and receive backstop pool tokens)
    * backstop burn

## Note
This is both for the Pendulum and Foucoco deployment

## Reference
<img width="557" alt="Screenshot 2024-05-30 at 12 48 54 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/65f8d68f-ded8-4427-b0ca-a1789726c58f">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/478?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by ebma** [comment]
What does 'not calculated properly' mean? Can you give an example when it fails? Is removing the buttons the best idea to solve this though?

**Comment by TorstenStueber** [comment]
The way it was defined in the code (and I did not change this anymore when I took it over): the max button selects the maximum amount of tokens you can deposit, i.e., 100% of your LP tokens. Similar for the 50% button.

However, that is not the actual maximum amount possible. In some situations you are not able to return all LP tokens because of some limits or because there are not enough tokens in the pool to return.

Here the argument is that the user would expect that the Max button does not select 100% of your LP tokens but the exact maximum of tokens you are able to return in this situation. 

This kind of problem happens for four operations:
* backstop pool withdrawal (return backstop pool LP tokens and receive backstop pool tokens)
* swap pool withdrawal (return swap pool LP tokens and receive swap pool tokens)
* backstop redeem (return swap pool LP tokens and receive backstop pool tokens)
* backstop burn (return backstop pool LP tokens and receive swap pool tokens)

There is no function in the smart contracts to calculate these maximum values (and we can't add them, otherwise they become too big for pallet contracts).

That means that we would need to do the calculation of the current maximum amount in the UI. This is not trivial and I wanted to leave it out in the initial version of the Nabla UI.

**Comment by TorstenStueber** [comment]
What I mean: we should remove the 50% and Max buttons for all these four operations and not just for backstop pool withdrawals (and stated in this ticket).

**Comment by prayagd** [comment]
@TorstenStueber got it, updated the ticket
