### ISSUE TITLE
Show the Portal PEN balance only for transferrable tokens

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#485]
## Context
Currently the balance shown in the top right corner for the portal UI, adds up all categories of token balances for ex. locked etc etc. This causes confusion because the transferrable balance could be different. 

## Requirement
* Show only the transferrable tokens as balance in the top right corner

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/485?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
We unfortunately have to leave the Nabla stuff out of scope here because it requires a change to our chain extensions. These changes have to happen to the runtime and are not a UI problem. @prayagd can you please create a ticket "Change chain extensions to return transferable balance" in the pendulum repository? It's okay if you keep the description short and mention this ticket here as a context. I can fill in the technical details once the ticket was created.
