### ISSUE TITLE
Enable PEN (Sol Peruano Digital) and ARS (Peso Digital) as Spacewalk asset on the portal on Pendulum

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#544]
#### Context
We are planning to PEN (Sol Peruano Digital) and ARS (Peso Digital) to Spacewalk assets. We need to enable assets on the portal and the dashboard once the [root transaction](https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/tasks/386) is completed.

Asset
- PEN (Sol Peruano Digital) 
- ARS (Peso Digital)

[asset details](https://api.anclap.com/.well-known/stellar.toml)

Asset Icons:
ARS - https://static.anclap.com/coin/ars.png
PEN - https://static.anclap.com/coin/pen.png

## Requirements
- [ ] Add PEN (Sol Peruano Digital) to the portal dashboard
- [ ] Add pricing for PEN 
- [ ] Add icon for PEN
- [ ] Add ARS (Peso Digital) to the portal dashboard
- [ ] Add pricing for ARS - Binance
- [ ] Add icon for ARS

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/544?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
@Sharqiewicz all we need to do for this is to make sure that the icons are available for the respective new currencies. The Spacewalk vault dropdown and asset dashboard should show these tokens automatically one a) a vault is registered and b) the asset registry metadata for these values is added on chain.

**Comment by Sharqiewicz** [comment]
Thanks @ebma for explaining :)

**Comment by annatekl** [comment]
Icons updated

**Comment by vadaynujra** [comment]
@ebma we don't have the vault creation tickets for the new assets. Since that would also require provisioning for some liquidity / collateral, will look into it later.

**Comment by ebma** [comment]
Should we add a label to this ticket that it's blocked or in draft?

**Comment by prayagd** [comment]
> Should we add a label to this ticket that it's blocked or in draft?


are there any more tickets required apart from [this](https://github.com/pendulum-chain/tasks/issues/387)

**Comment by prayagd** [comment]
@vadaynujra can you share the price we need for the ARS asset and also is there any preference with the PEN asset?

**Comment by vadaynujra** [comment]
For Argentinian Peso (ARS), the anchor uses the [Blue Rate](https://bluedollar.net/) and so we will go with the same. Checking the price of the asset on the Stellar side confirms the same (screenshot).
@ebma @prayagd using this information, can you find the specific feed on Polygon?

![image](https://github.com/user-attachments/assets/14179578-0834-4c6b-9088-4c57808408c9)

The Peruvian Sol (PEN) doesn't have this challenge and we can use the [standard rate](https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=PEN).

**Comment by ebma** [comment]
That's a problem. When I query the price from polygon.io for USD to ARS, I get an exchange rate of 1 USD = 968.7406 ARS. I checked all tickers and they don't have any ticker for the blue dollar. 

I don't know how niche this blue dollar is but the only way I see to get the exchange rate on chain right now is to handle custom handling to the batching server. We should have already clarified this before setting up the PEN and ARS price feeds we already added. Because now we probably have to unregister the ARS price again and replace it with ARSB.

**Comment by vadaynujra** [comment]
> to handle custom handling to the batching server

How would it be handed? Different price source than Polygon e.g. Stellar AMM or some other off chain option? Rr something else?

> We should have already clarified this before setting up the PEN and ARS price feeds we already added.

True, especially since we always knew about this dual price for ARS. What does unregistering the price mean? Not the same as the asset registry right?

**Comment by ebma** [comment]
Yes, we first have to find a different provider where we can reliably source the USD/ARSB price from. I didn't see many, but we have to look into this. I doubt that Polygon.io would be willing to add that for us. 

> What does unregistering the price mean? Not the same as the asset registry right?

This depends how we want to set it up. In theory, we can cut some corners with the on-chain configuration and leave everything as is by only changing the batching server to serve the ARSB price instead of ARS. While not technically correct, I guess it would be fine for our use case. This assumes that we never ever want to have access to both ARS and ARSB prices on-chain.

**Comment by vadaynujra** [comment]
Found a feed on Binance spot rate: https://www.binance.com/en/trade/USDT_ARS?type=spot

**Comment by vadaynujra** [comment]
@prayagd update the icons.

**Comment by prayagd** [comment]
> @prayagd update the icons.

Done
